export const VITE_FRONTEND_URL= "https://www.planit-travel.me"
export const VITE_BACKEND_URL= "https://api.planit-travel.me"
export const LOCAL_FRONTEND_URL= "http://localhost:5173"
export const LOCAL_BACKEND_URL= "http://localhost:3000"
export const AI_BACKEND_URL= "https://www.ai.planit-travel.me"
